# Generated by Django 4.2.5 on 2023-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coupan_remove_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupan',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupan',
            name='expiry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
