# Generated by Django 4.2.5 on 2023-10-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_coupan_value_alter_coupan_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(default=0)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.cart')),
            ],
        ),
    ]
