# Generated by Django 4.2.3 on 2023-09-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
